version: 2.1
    
orbs:
 android: circleci/android@0.2.0
  
jobs:
  build:
    executor: android/android
        
    steps:
      - checkout
      - run:
          name: Export Google Services Json
          command: echo 'export GOOGLE_SERVICES_JSON="$GOOGLE_SERVICES_JSON"' >> $BASH_ENV
      - run:
          name: Decode Google Services Json
          command: echo $GOOGLE_SERVICES_JSON | base64 -di > app/google-services.json
      - run:
          command: ./gradlew build
